<?php

return [
    'about' => [
        'meta_description' => 'Novara News est une rédaction numérique indépendante et multilingue dédiée à l\'IA, à la cybersécurité et aux technologies émergentes, avec des standards éditoriaux professionnels.',
        'paragraphs' => [
            'Novara News est un média numérique indépendant consacré aux sujets qui définissent l\'ère technologique : grands modèles de langage et politique de l\'IA, compétition dans les semi-conducteurs, infrastructures cloud, incidents de cybersécurité, appareils grand public, logiciels d\'entreprise, jeu vidéo et les forces économiques qui remodèlent tout cela.',
            'Nous publions en cinq langues — anglais, turc, allemand, français et espagnol. Chaque édition est conçue pour ses lecteurs : les titres reflètent le registre de la langue, les nuances franchissent correctement la barrière linguistique, et les structures d\'URL sont natives à chaque marché. Aucun article de ce site n\'est le résultat d\'une traduction automatique à partir d\'un fichier source unique.',
            'Notre couverture suit les rubriques de la navigation : recherche et gouvernance de l\'IA, développements dans les puces et le cloud, écosystèmes mobiles, logiciels d\'entreprise et grand public, incidents de sécurité et matériel. Nous choisissons les sujets selon leur vérifiabilité, leur intérêt public et leur proportionnalité — pas selon les demandes de partenaires commerciaux.',
            'Indépendance : la rédaction sélectionne et cadre la couverture sans instruction des annonceurs, sponsors ou partenaires commerciaux. Tout contenu sponsorisé ou de marque, s\'il existe sur le site, est clairement séparé du contenu éditorial et identifié conformément à notre politique.',
            'Vérification : nous travaillons avec des sources nommées, des documents primaires, des déclarations officielles de régulateurs et de fabricants, des agences reconnues, et — pour les sujets scientifiques — de la littérature évaluée par les pairs. Nous distinguons clairement ce qui est confirmé, ce qui est attribué, ce qui relève de l\'analyse, et ce qui est spéculation.',
            'Transparence sur l\'IA : des outils peuvent aider à compiler des recherches ou structurer des brouillons. Des rédacteurs humains examinent et valident chaque version publiable ; ils portent l\'entière responsabilité de l\'exactitude factuelle, du contexte et de l\'équité. Toute contribution significative de l\'IA à la production est communiquée ouvertement aux lecteurs.',
            'Les corrections font partie intégrante d\'un journalisme crédible et ne sont pas une faiblesse. Lorsque nous modifions le fond d\'un article, nous publions une note de correction datée expliquant l\'erreur et ce qui la remplace. Les corrections typographiques sans impact sur le sens peuvent être effectuées discrètement.',
            'Ton et déontologie : nous ne publions pas de titres qui exagèrent la certitude, amplifient l\'alarme ou réduisent des questions techniques complexes à une fausse simplicité. La vie privée, la sécurité et la dignité humaine — en particulier des personnes privées — guident chaque décision éditoriale sur ce que nous publions et comment.',
            'Accessibilité et transparence : nous maintenons des URL d\'articles stables, des horodatages visibles de publication et de mise à jour, des pages complètes À propos, Politique éditoriale, Contact, Confidentialité et Cookies, ainsi que des données structurées compatibles avec Google Actualités, la Recherche Google et les principales plateformes d\'agrégation.',
            'Publicité et mesure d\'audience : lorsque Google Analytics, Google AdSense ou des services comparables sont actifs, leur déploiement respecte nos politiques de confidentialité et de cookies ainsi que les exigences de consentement applicables. Aucun tag commercial n\'influence les décisions éditoriales.',
            'Retours : les demandes de correction sérieuses appuyées par des sources primaires, les signalements d\'actualité et les divulgations responsables de failles de sécurité sont les bienvenus via nos canaux de contact. Nous priorisons les contestations de bonne foi accompagnées de références vérifiables.',
            'Correspondance juridique et presse : les courriers institutionnels doivent clairement indiquer l\'entité, la juridiction et l\'objet. Nous ne sommes pas en mesure de fournir de conseils juridiques via notre formulaire public.',
        ],
    ],

    'editorial-policy' => [
        'meta_description' => 'Politique éditoriale de Novara News : indépendance, vérification des sources, divulgation de l\'IA, processus de correction et séparation stricte entre activité commerciale et décisions rédactionnelles.',
        'paragraphs' => [
            'Cette politique éditoriale s\'applique à toutes les éditions linguistiques et rubriques de Novara News. Elle décrit comment nous assignons, vérifions, corrigeons et étiquetons nos contenus afin que lecteurs et plateformes puissent comprendre les standards qui sous-tendent chaque article publié.',
            'Mission : nous couvrons l\'intelligence artificielle et la technologie pour un large public ayant besoin d\'informations fiables et bien contextualisées — fondateurs, observateurs de politiques, ingénieurs et lecteurs curieux de tout horizon. Notre exigence est l\'exactitude et la proportionnalité, non les cycles de surenchère ni les influences commerciales masquées.',
            'Indépendance : la rédaction choisit les sujets selon des faits vérifiables, leur importance éditoriale et les besoins du lectorat. Aucun annonceur, sponsor, gouvernement ou parti politique ne peut dicter les titres, la sélection des sujets ou le cadrage du journalisme indépendant. Les relations commerciales sont strictement séparées des décisions rédactionnelles.',
            'Exactitude et clarté : nous rendons compte honnêtement des niveaux de certitude. Les informations en développement sont mises à jour au fil des faits. Les analyses et formats explicatifs sont rédigés ou signalés de façon à ce que les lecteurs sachent quand l\'interprétation prend le pas sur le fait établi.',
            'Hiérarchie des sources : nous privilégions les sources citées nommément, les documents primaires et les agences de presse sérieuses. L\'anonymat est rare, doit satisfaire à des critères internes stricts et nécessite une justification éditoriale documentable.',
            'Divulgation de l\'IA : lorsque des outils génératifs ou d\'assistance ont significativement contribué à la recherche, à la rédaction ou au traitement de données, cela doit être signalé. La rédaction examine ces déclarations et les porte à la connaissance des lecteurs lorsque les seuils de la politique sont atteints.',
            'Processus de correction : les erreurs substantielles sont corrigées rapidement avec une note de correction visible. Si la conclusion d\'un article change de façon significative, nous en expliquons la raison. Les rétractions sont réservées aux manquements factuels ou éthiques graves et traitées avec une totale transparence.',
            'Intégrité visuelle : les images, graphiques et captures d\'écran sont légendés avec précision. Les contenus illustratifs ou simulés sont clairement identifiés pour ne pas être confondus avec des preuves documentaires.',
            'Sécurité : nous ne publions pas d\'instructions permettant de causer des préjudices graves, de données d\'identification non masquées, ni de données personnelles gratuites. La couverture des sujets de sécurité équilibre soigneusement l\'intérêt public et les normes de divulgation responsable.',
            'Séparation rédaction et publicité : les unités commerciales ne peuvent pas promettre ni se voir accorder une couverture favorable. Les formats commerciaux, encarts affiliés ou publications partenaires sont clairement distincts des contenus journalistiques et respectent toutes les obligations de signalisation.',
            'Diversité et proportionnalité : la technologie touche les populations du monde entier ; dans la mesure où l\'actualité le permet, nous cherchons une couverture géographiquement et démographiquement représentative, sans créer de faux équilibre sur des faits bien établis.',
            'Contenus tiers et utilisateurs : les fonctions de commentaires ou de communauté, si elles existent, sont modérées selon des règles publiées. Les propos d\'utilisateurs non vérifiés ne valent pas un reportage validé par la rédaction.',
            'Mises à jour : cette politique peut évoluer avec les avancées technologiques, la réglementation et les attentes des plateformes. Les changements substantiels seront reflétés sur cette page avec une date de référence actualisée.',
        ],
    ],

    'privacy' => [
        'meta_description' => 'Politique de confidentialité de Novara News : quelles données personnelles nous traitons, pourquoi, avec quels partenaires et comment exercer vos droits en matière de protection des données.',
        'paragraphs' => [
            'Cette politique de confidentialité explique comment Novara News (nous) traite les informations lorsque vous visitez notre site, utilisez des formulaires ou accédez à des fonctionnalités liées à un compte ou à des communications par e-mail. Nous traitons les données personnelles de manière licite, transparente et proportionnée.',
            'Responsable du traitement : l\'organisation qui exploite Novara News sur le domaine où cette politique est publiée. Les coordonnées pour les demandes relatives à la confidentialité figurent sur notre page Contact.',
            'Les données que nous pouvons collecter comprennent : des données techniques telles qu\'adresses IP tronquées, user-agents de navigateur, classe d\'appareil et géographie approximative dérivée de signaux réseau ; des données d\'utilisation telles que pages consultées et événements d\'interaction ; ainsi que les informations que vous soumettez volontairement via des formulaires — par exemple, nom, adresse e-mail et texte du message.',
            'Les messages de contact et les signalements sont utilisés pour vous répondre, assurer le suivi et conserver un dossier proportionné à des fins de conformité ou de traitement des réclamations. Nous ne vendons pas de données personnelles et nous n\'utilisons pas les canaux de signalement pour constituer des listes de marketing non sollicité.',
            'Nous faisons appel à des sous-traitants, notamment des hébergeurs, des services CDN et de sécurité (par exemple Cloudflare), des partenaires d\'envoi d\'e-mails, des prestataires d\'analyse et des partenaires publicitaires. Tous sont liés par contrat à ne traiter les données que sur instructions documentées.',
            'Les cookies et technologies similaires comprennent : des cookies strictement nécessaires pour la sécurité, l\'équilibrage de charge, la mémorisation du consentement et la navigation principale ; des cookies de préférences qui peuvent mémoriser des choix comme le thème de couleur ou la langue ; des cookies d\'analyse qui mesurent les performances agrégées du site ; et — le cas échéant — des cookies publicitaires pour le plafonnement de fréquence, la prévention de la fraude et la mesure dans des réseaux comme Google AdSense, selon vos choix et les exigences régionales applicables.',
            'Google Analytics : lorsqu\'il est activé, nous pouvons utiliser Google Analytics 4 pour analyser le trafic agrégé. Vous pouvez gérer vos préférences en matière d\'analyse et de publicité via les paramètres du navigateur, les outils de consentement régionaux disponibles et les pages d\'opt-out des éditeurs de services.',
            'Google AdSense et tags publicitaires similaires : lorsqu\'ils sont actifs, les partenaires publicitaires peuvent traiter des données conformément à leurs propres politiques. Nous configurons les tags pour honorer les signaux de consentement applicables et la réglementation en vigueur. Le contenu éditorial est produit indépendamment du ciblage publicitaire.',
            'Les bases légales peuvent inclure les intérêts légitimes (exploitation sécurisée, compréhension de l\'audience, prévention de la fraude), l\'exécution d\'un contrat (répondre à vos demandes), et le consentement lorsqu\'il est requis pour les cookies non essentiels ou le marketing direct.',
            'La conservation est limitée aux besoins opérationnels. Les journaux serveur et la télémétrie de sécurité sont conservés sur des fenêtres glissantes courtes, sauf si une réponse à incident ou une obligation légale nécessite une durée plus longue. La correspondance n\'est conservée que le temps nécessaire pour traiter la demande et satisfaire aux obligations réglementaires.',
            'Transferts internationaux : si des données quittent votre pays, nous mettons en place des garanties appropriées telles que des clauses contractuelles types ou des mesures équivalentes, selon les exigences du droit applicable.',
            'Sécurité : nous appliquons des contrôles conformes aux standards du secteur, notamment le chiffrement TLS, les restrictions d\'accès, la supervision et la diligence raisonnable vis-à-vis des fournisseurs. Aucun service en ligne n\'est entièrement exempt de risques ; veuillez signaler toute vulnérabilité supposée via nos canaux de contact.',
            'Vos droits : selon votre juridiction, vous pouvez demander l\'accès, la rectification, l\'effacement, la limitation, vous opposer au traitement ou demander la portabilité de vos données. Nous pouvons vérifier votre identité avant de donner suite. Vous avez également le droit d\'introduire une réclamation auprès de votre autorité de contrôle.',
            'Enfants : nos services sont destinés aux adultes. Nous ne collectons pas sciemment d\'informations personnelles concernant des enfants sans consentement approprié. Veuillez nous contacter si vous pensez que des données concernant un mineur ont été soumises par erreur.',
            'Modifications : nous mettrons à jour cette politique lorsque nos pratiques, nos partenaires ou les lois applicables évolueront. L\'utilisation continue après des mises à jour substantielles vaut acceptation dans la mesure permise par la loi ; les changements importants seront signalés sur le site.',
        ],
    ],

    'cookies' => [
        'meta_description' => 'Utilisation des cookies par Novara News : fonctionnement essentiel du site, mesure d\'audience, préférences publicitaires et options pratiques pour gérer votre consentement.',
        'paragraphs' => [
            'Les cookies et technologies de stockage similaires aident Novara News à fonctionner en toute sécurité, à mémoriser vos préférences, à mesurer les tendances de l\'audience et — lorsqu\'ils sont activés — à soutenir une publicité responsable. Cette page présente chaque catégorie et vos options de gestion.',
            'Les cookies strictement nécessaires activent les fonctions de sécurité, répartissent la charge serveur, maintiennent l\'intégrité des sessions pour les outils d\'administration et respectent les choix de consentement que vous avez déjà exprimés. Les désactiver peut altérer des fonctionnalités essentielles du site.',
            'Les cookies de préférences mémorisent vos choix tels que le thème de couleur ou les raccourcis de langue, lorsqu\'ils sont disponibles. Leur usage est limité à l\'amélioration de l\'ergonomie sur nos propres domaines et n\'est pas utilisé pour le suivi inter-sites.',
            'Les cookies d\'analyse fournissent des statistiques agrégées sur la fréquentation — rubriques populaires, parcours de navigation, types d\'appareils approximatifs. Nous utilisons ces données pour améliorer nos décisions éditoriales et techniques, non pour constituer des profils individuels à des fins de marketing non lié à notre activité.',
            'Les cookies publicitaires, lorsque AdSense ou des réseaux comparables sont actifs, peuvent mesurer les impressions, limiter la fréquence d\'exposition et détecter le trafic invalide. Les partenaires traitent les données selon leurs propres politiques publiées ; consultez les ressources de Google sur la publicité et la confidentialité pour les détails relatifs aux services Google.',
            'Gestion de vos cookies : vous pouvez supprimer ou bloquer les cookies dans les paramètres de votre navigateur, utiliser les pages d\'opt-out des fournisseurs, et — lorsque nous affichons une interface de consentement — retirer ou mettre à jour votre consentement à tout moment. Bloquer les cookies publicitaires ne supprime pas toutes les annonces dans toutes les configurations, mais limite les expériences publicitaires personnalisées.',
            'Le signal Do Not Track du navigateur n\'est pas appliqué de manière uniforme dans le secteur. Nous appliquons néanmoins l\'ensemble des contrôles et informations décrits dans cette politique et dans notre politique de confidentialité.',
            'Mises à jour : les catégories de cookies que nous utilisons peuvent évoluer avec les prestataires, les services ou la réglementation. Nous vous recommandons de consulter cette page régulièrement ; les changements importants seront annoncés sur le site le cas échéant.',
        ],
    ],

    'contact' => [
        'meta_description' => 'Contactez Novara News pour des corrections, des signalements confidentiels, des demandes presse, des questions de confidentialité et des partenariats liés à notre couverture de l\'IA et des technologies.',
        'contact_label' => 'Contact',
        'paragraphs' => [
            'Utilisez le formulaire sécurisé ci-dessous pour contacter Novara News à propos de demandes de correction, de signalements d\'actualité, de demandes relatives à la vie privée ou aux droits sur les données, de sollicitations presse et médias, de questions de partenariat ou de licence, ainsi que de problèmes techniques affectant l\'accès au site.',
            'Corrections : indiquez l\'URL ou le titre de l\'article, le passage concerné et des liens vers les sources primaires ou documents officiels étayant votre correction. Des dossiers clairs et bien documentés permettent aux rédacteurs de vérifier rapidement et, si nécessaire, de publier une version actualisée accompagnée d\'une note de correction.',
            'Signalements d\'actualité : décrivez ce qui s\'est passé, où et quand, en joignant les éléments que vous pouvez partager en toute sécurité — documents, journaux, chronologie des événements. Nous évaluons les signalements selon leur vérifiabilité et leur intérêt public réel. Les demandes de confidentialité sont prises au sérieux, mais ne peuvent pas toujours être garanties.',
            'Vie privée et droits sur les données : précisez l\'action demandée — accès, rectification, effacement, opposition ou autre droit — et l\'adresse e-mail associée à votre interaction avec nous. Une vérification d\'identité pourra être demandée avant de traiter les demandes sensibles.',
            'Failles de sécurité : si vous pensez avoir découvert une vulnérabilité dans nos systèmes, n\'allez pas au-delà d\'une preuve de concept. Transmettez les étapes de reproduction via notre canal de contact en indiquant l\'objet Sécurité.',
            'Les courriers commerciaux et juridiques doivent indiquer le nom complet de l\'entité, la juridiction et une référence de dossier. Nous examinons toute correspondance mais ne pouvons pas dispenser de conseils juridiques via notre formulaire public.',
            'Nous nous efforçons d\'accuser réception des signalements factuels sérieux dans un délai raisonnable. Le volume et les exigences de vérification peuvent allonger les délais de réponse aux retours généraux ou aux demandes non urgentes.',
        ],
    ],
];
