<?php

return [
    'about' => [
        'meta_description' => 'Novara News ist eine unabhängige mehrsprachige Technologieredaktion mit Fokus auf KI, Cybersicherheit und digitale Wirtschaft – professionelle Redaktionsstandards in fünf Sprachen.',
        'paragraphs' => [
            'Novara News ist ein unabhängiges digitales Nachrichtenmedium für die Themen, die das Technologiezeitalter prägen: große Sprachmodelle und KI-Politik, Halbleiterwettbewerb, Cloud-Infrastruktur, Cybersicherheitsvorfälle, Verbrauchergeräte, Unternehmenssoftware, Gaming und die wirtschaftlichen Kräfte, die all das verändern.',
            'Wir publizieren in fünf Sprachen: Englisch, Türkisch, Deutsch, Französisch und Spanisch. Jede Sprachausgabe wird für ihre Leserinnen und Leser erstellt – Überschriften folgen dem jeweiligen Sprachregister, Nuancen überqueren die Sprachgrenze korrekt, und URL-Strukturen sind für jeden Markt nativ gestaltet. Kein Artikel auf dieser Website ist das Ergebnis automatischer Übersetzung aus einer einzigen Quelldatei.',
            'Unser Themenspektrum folgt den Kategorien in der Navigation: KI-Forschung und Regulierung, Chip- und Cloud-Entwicklungen, mobile Ökosysteme, Unternehmens- und Verbrauchersoftware, Sicherheitsvorfälle sowie Hardware. Wir wählen Themen nach Überprüfbarkeit, öffentlichem Interesse und Verhältnismäßigkeit – nicht nach kommerziellen Buchungsinteressen.',
            'Unabhängigkeit: Die Redaktion wählt und rahmt Berichterstattung ohne Weisungen von Werbetreibenden, Sponsoren oder kommerziellen Partnern. Gesponserte oder markenbezogene Inhalte, sofern vorhanden, sind klar von redaktionellen Nachrichten getrennt und gemäß unserer Richtlinie gekennzeichnet.',
            'Verifikation: Wir arbeiten mit namentlich genannten Quellen, Primärdokumenten, offiziellen Behörden- und Herstellermitteilungen, seriösen Nachrichtenagenturen sowie – in der Wissenschaftsberichterstattung – mit begutachteter Fachliteratur. Wir machen deutlich, was bestätigt, was zugeschrieben, was Analyse und was Spekulation ist.',
            'KI-Offenlegung: KI-Werkzeuge können bei Recherchezusammenfassung oder Entwurfsstruktur unterstützen. Jede veröffentlichte Fassung wird von menschlichen Redakteurinnen und Redakteuren geprüft und freigegeben; sie tragen die Verantwortung für Richtigkeit, Kontext und Fairness. Wesentliche KI-Beteiligung an der Produktion wird den Lesenden gegenüber offen kommuniziert.',
            'Korrekturen gehören zur glaubwürdigen Berichterstattung und sind kein Zeichen von Schwäche. Ändern wir den inhaltlichen Kern eines Berichts, veröffentlichen wir eine datierte Korrekturnotiz mit Erläuterung des Fehlers und der Aktualisierung. Reine Schreibkorrekturen ohne Bedeutungsänderung können ohne gesonderte Meldung vorgenommen werden.',
            'Ton und Ethik: Wir vermeiden Überschriften, die Gewissheit, Ausmaß oder Risiken verzerrt darstellen. Datenschutz, Sicherheit und Menschenwürde – besonders schutzbedürftiger Personen – sowie Verhältnismäßigkeit beim Umgang mit technischen oder sicherheitsrelevanten Details sind leitend.',
            'Transparenz und Auffindbarkeit: Wir pflegen stabile Artikel-URLs, sichtbare Veröffentlichungs- und Aktualisierungszeitpunkte, vollständige About-, Redaktionsrichtlinien-, Kontakt-, Datenschutz- und Cookie-Seiten sowie strukturierte Daten, die mit Google News, Google Suche und führenden Nachrichtenplattformen kompatibel sind.',
            'Werbung und Analyse: Setzen wir Google Analytics, Google AdSense oder vergleichbare Dienste ein, geschieht dies gemäß unserer Datenschutz- und Cookie-Richtlinie sowie den geltenden Einwilligungsanforderungen. Kein kommerzielles Tag beeinflusst redaktionelle Entscheidungen.',
            'Rückmeldungen: Seriöse Korrekturhinweise mit Quellenbelegen, Nachrichtentipps und verantwortungsvolle Sicherheitsmeldungen sind über unsere Kontaktwege willkommen. Wir priorisieren gut begründete, sachlich fundierte Einwände mit überprüfbaren Nachweisen.',
            'Rechtliches und Presse: Organisationsschreiben sollten die Institution, Rechtsordnung und den Betreff klar benennen. Rechtsberatung können wir über das allgemeine Kontaktformular nicht leisten.',
        ],
    ],

    'editorial-policy' => [
        'meta_description' => 'Redaktionsrichtlinie von Novara News: Unabhängigkeit, Quellenprüfung, KI-Offenlegung, Korrekturverfahren und strikte Trennung kommerzieller Aktivitäten von redaktionellen Entscheidungen.',
        'paragraphs' => [
            'Diese Redaktionsrichtlinie gilt für alle Sprachausgaben und Rubriken von Novara News. Sie beschreibt, wie wir Themen vergeben, überprüfen, korrigieren und kennzeichnen, damit Leserinnen, Leser und Plattformen unsere Standards nachvollziehen können.',
            'Redaktionelle Ausrichtung: Wir berichten zu KI und Technologie für ein breites Publikum, das verlässlichen Kontext benötigt – Gründerinnen und Gründer, Policy-Beobachtende, Ingenieurinnen und Ingenieure und neugierige Leserinnen und Leser jeder Art. Unser Maßstab ist Genauigkeit und Verhältnismäßigkeit – keine Hype-Zyklen, kein verdeckter kommerzieller Einfluss.',
            'Unabhängigkeit: Die Redaktion wählt Themen nach überprüfbaren Fakten, redaktioneller Bedeutung und Publikumsbedarf. Kein Werbetreibender, Sponsor, staatliche Stelle oder Partei darf Überschriften, Themenauswahl oder die Einordnung unabhängiger Berichterstattung bestimmen. Kommerzielle Beziehungen werden strikt von redaktionellen Entscheidungen getrennt.',
            'Genauigkeit und Klarheit: Wir geben Unsicherheitsgrade ehrlich wieder. Laufende Meldungen werden aktualisiert, wenn sich Fakten konkretisieren. Analysen und Erklärformate sind so verfasst oder gekennzeichnet, dass Lesende erkennen, wann Interpretation statt bestätigter Tatsachen im Vordergrund steht.',
            'Quellenhierarchie: Wir bevorzugen namentlich genannte Quellen, Primärdokumente und seriöse Nachrichtenagenturen. Anonyme Quellen sind selten, müssen strenge interne Kriterien erfüllen und eine dokumentierbare redaktionelle Begründung haben.',
            'KI-Offenlegung: Wenn generative oder assistierende KI-Werkzeuge Recherche, Textentwurf oder Datenarbeit wesentlich geprägt haben, muss dies gemeldet werden. Die Redaktion prüft diese Angaben und macht sie den Lesenden gegenüber transparent, wenn Richtlinienschwellen erreicht sind.',
            'Korrekturverfahren: Inhaltliche Fehler werden zügig mit sichtbarem Korrekturvermerk behoben. Ändert sich die Schlussfolgerung eines Berichts erheblich, erläutern wir den Grund. Rücknahmen bleiben schwerwiegenden sachlichen oder ethischen Verstößen vorbehalten und werden transparent gehandhabt.',
            'Integrität visueller Inhalte: Bilder, Grafiken und Screenshots sind korrekt beschriftet. Illustratives oder simuliertes Material wird klar gekennzeichnet, damit es nicht als dokumentarischer Beleg missverstanden wird.',
            'Sicherheit und Schutz: Wir veröffentlichen keine Anleitungen, die schwerwiegenden Schaden ermöglichen, keine ungeschwärzten Zugangsdaten und keine unnötigen personenbezogenen Daten. Bei der Sicherheitsberichterstattung wägen wir öffentliches Interesse und verantwortungsvolle Offenlegung sorgfältig ab.',
            'Trennung von Werbung und Redaktion: Kommerzielle Einheiten dürfen keine wohlwollende Berichterstattung versprechen oder einfordern. Commerce-Formate, Affiliate-Boxen und Partner-Beiträge sind visuell und redaktionell klar von journalistischen Texten getrennt und entsprechend gekennzeichnet.',
            'Vielfalt und Verhältnismäßigkeit: Technologie wirkt global; soweit es der Nachrichtenfluss erlaubt, streben wir geografisch und demografisch ausgewogene Berichterstattung an – ohne Scheinausgewogenheit bei gut belegten Fakten zu erzeugen.',
            'Drittinhalte und Nutzerinhalte: Kommentar- oder Community-Funktionen werden nach veröffentlichten Regeln moderiert. Nicht überprüfte Nutzeräußerungen gelten nicht als redaktionell validierte Berichterstattung.',
            'Aktualisierungen: Diese Richtlinie kann sich mit Technologieentwicklung, Regulierung und Plattformerwartungen weiterentwickeln. Wesentliche Änderungen werden auf dieser Seite mit einem aktuellen Referenzdatum ausgewiesen.',
        ],
    ],

    'privacy' => [
        'meta_description' => 'Datenschutzerklärung von Novara News: welche personenbezogenen Daten wir verarbeiten, zu welchem Zweck, mit welchen Partnern und wie Sie Ihre Rechte ausüben können.',
        'paragraphs' => [
            'Diese Datenschutzerklärung erläutert, wie Novara News („wir") Informationen verarbeitet, wenn Sie unsere Website besuchen, Formulare verwenden oder Funktionen mit Konto- oder E-Mail-Bezug nutzen. Wir verarbeiten personenbezogene Daten rechtmäßig, transparent und verhältnismäßig.',
            'Verantwortliche Stelle: Verantwortlich ist die Organisation, die Novara News unter der Domain betreibt, auf der diese Erklärung veröffentlicht wird. Kontaktdaten für datenschutzbezogene Anfragen finden Sie auf unserer Kontaktseite.',
            'Erhobene Daten können umfassen: technische Daten wie gekürzte IP-Adressen, Browser-User-Agent, Geräteklasse und ungefähre geografische Herkunft aus Netzwerksignalen; Nutzungsdaten wie aufgerufene Seiten und Interaktionsereignisse; sowie Informationen, die Sie freiwillig über Formulare übermitteln – zum Beispiel Name, E-Mail-Adresse und Nachrichtentext.',
            'Kontakt- und Hinweiseingaben dienen der Beantwortung Ihrer Anfrage, der Nachverfolgung und der verhältnismäßigen Dokumentation für Compliance- oder Beschwerdezwecke. Wir verkaufen keine personenbezogenen Daten und nutzen Hinweiskanäle nicht für unaufgeforderte Marketinglisten.',
            'Wir setzen Auftragsverarbeiter ein, darunter Hosting-Anbieter, CDN- und Sicherheitsdienste (z. B. Cloudflare), E-Mail-Zustelldienste, Analyseanbieter und Werbepartner. Alle Verarbeiter sind vertraglich verpflichtet, Daten ausschließlich auf dokumentierte Weisung zu verarbeiten.',
            'Cookies und ähnliche Technologien umfassen: technisch notwendige Cookies für Sicherheit, Lastverteilung, Einwilligungsspeicherung und grundlegende Navigation; Präferenz-Cookies, die Einstellungen wie Farbschema oder Sprache speichern; Analytics-Cookies zur aggregierten Messung der Website-Nutzung sowie – wo zutreffend – Werbe-Cookies für Frequenzsteuerung, Betrugserkennung und Reichweitenmessung in Netzwerken wie Google AdSense, abhängig von Ihren Einstellungen und regionalen Anforderungen.',
            'Google Analytics: Bei Aktivierung können wir Google Analytics 4 zur aggregierten Verkehrsanalyse einsetzen. Ihre Analyse- und Werbeeinstellungen verwalten Sie über die Browsereinstellungen, regionale Consent-Tools sowie Opt-out-Seiten der Anbieter.',
            'Google AdSense und vergleichbare Werbetags: Bei Aktivierung können Werbepartner Daten gemäß ihren eigenen Richtlinien verarbeiten. Wir konfigurieren Tags so, dass sie geltende Einwilligungssignale und gesetzliche Vorgaben einhalten. Redaktionelle Inhalte entstehen unabhängig von Werbetargeting.',
            'Rechtsgrundlagen können sein: berechtigte Interessen (sicherer Betrieb, Zielgruppenverständnis, Betrugsprävention), Vertragserfüllung (Bearbeitung Ihrer Anfragen) sowie – wo erforderlich – Einwilligung für nicht notwendige Cookies oder Direktmarketing.',
            'Speicherfristen richten sich nach betrieblichen Erfordernissen. Server-Logs und Sicherheitstelemetrie werden in kurzen, rollierenden Zeitfenstern aufbewahrt, sofern nicht Incident-Response-Anforderungen oder gesetzliche Aufbewahrungspflichten längere Fristen erfordern. Korrespondenz wird nur so lange gespeichert, wie es zur Bearbeitung der Anfrage und zur Erfüllung regulatorischer Verpflichtungen notwendig ist.',
            'Drittlandübermittlungen: Verlassen Daten Ihr Land, setzen wir geeignete Schutzmaßnahmen wie Standardvertragsklauseln oder gleichwertige Mechanismen ein, soweit das anwendbare Recht dies vorschreibt.',
            'Sicherheit: Wir setzen branchenübliche Maßnahmen ein, darunter TLS-Verschlüsselung, Zugriffskontrollen, Monitoring und Anbieter-Sorgfaltspflichten. Kein Online-Dienst ist vollständig risikofrei; mutmaßliche Schwachstellen melden Sie bitte über unsere Kontaktwege.',
            'Ihre Rechte: Je nach Rechtsordnung können Sie Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch oder Datenübertragbarkeit beantragen. Zur Identitätsverifizierung können wir vor der Bearbeitung auffordern. Beschwerden richten Sie an Ihre zuständige Aufsichtsbehörde.',
            'Kinder: Unsere Angebote richten sich an Erwachsene. Wir erheben wissentlich keine Daten Minderjähriger ohne geeignete Einwilligung. Wenden Sie sich an uns, wenn Sie glauben, dass irrtümlich Daten eines Kindes übermittelt wurden.',
            'Änderungen: Wir aktualisieren diese Erklärung, wenn sich Praktiken, Partner oder gesetzliche Vorgaben ändern. Fortgesetzte Nutzung nach Änderungen kann – soweit rechtlich zulässig – als Zustimmung gewertet werden; wesentliche Änderungen kündigen wir auf der Website an.',
        ],
    ],

    'cookies' => [
        'meta_description' => 'Cookie-Informationen von Novara News: notwendige Funktionen, Reichweitenmessung, Werbepräferenzen und Steuerungsmöglichkeiten für Ihre Einwilligung.',
        'paragraphs' => [
            'Cookies und ähnliche Speichertechnologien helfen Novara News, sicher zu funktionieren, Ihre Einstellungen zu speichern, Publikumstrends zu messen und – wenn aktiviert – verantwortungsvolle Werbung zu unterstützen. Diese Seite erläutert jede Kategorie und Ihre Verwaltungsoptionen.',
            'Technisch notwendige Cookies ermöglichen Sicherheitsfunktionen, Lastverteilung, Admin-Sitzungen und die Speicherung Ihrer Einwilligungsentscheidungen. Deren Deaktivierung kann wesentliche Bereiche der Website beeinträchtigen.',
            'Präferenz-Cookies speichern Einstellungen wie Farbschema oder Sprachkürzel. Ihr Einsatz beschränkt sich auf die Verbesserung der Nutzerfreundlichkeit auf unseren Domains und dient nicht der websiteübergreifenden Nachverfolgung.',
            'Analytics-Cookies liefern aggregierte Leserstatistiken – populäre Rubriken, Navigationspfade und ungefähre Geräteklassen. Diese Daten nutzen wir zur Weiterentwicklung unserer redaktionellen und technischen Angebote, nicht zur Erstellung individueller Nutzerprofile für branchenfremde Werbezwecke.',
            'Werbe-Cookies, wenn AdSense oder vergleichbare Werbenetzwerke aktiv sind, können Impressionen messen, Frequenz begrenzen und invaliden Traffic erkennen. Partner verarbeiten Daten gemäß ihren eigenen Richtlinien – Details zu Google-Diensten finden Sie in Googles Ressourcen zu Werbung und Datenschutz.',
            'Ihre Verwaltungsoptionen: Cookies löschen oder blockieren in den Browsereinstellungen, Anbieter-Opt-outs nutzen, und – falls wir eine Consent-Oberfläche anbieten – Ihre Einwilligung jederzeit widerrufen oder anpassen. Das Blockieren von Werbe-Cookies entfernt Anzeigen nicht in jeder Konfiguration, schränkt aber die Personalisierung ein.',
            'Das „Do Not Track"-Signal wird branchenweit nicht einheitlich umgesetzt. Wir wenden dennoch alle in dieser Richtlinie und in unserer Datenschutzerklärung beschriebenen Kontrollmechanismen an.',
            'Aktualisierungen: Cookie-Kategorien können sich mit Partnern, Diensten oder Regulierungsvorgaben ändern. Wir empfehlen, diese Seite regelmäßig zu überprüfen; wesentliche Änderungen werden gegebenenfalls auf der Website angekündigt.',
        ],
    ],

    'contact' => [
        'meta_description' => 'Kontakt zu Novara News: Korrekturen, vertrauliche Hinweise, Presseanfragen, Datenschutzanliegen und Partnerschaften rund um unseren KI- und Technologiejournalismus.',
        'contact_label' => 'Kontakt',
        'paragraphs' => [
            'Nutzen Sie das sichere Formular für Korrekturwünsche, Nachrichtentipps, Datenschutz- und Datenrechtsanfragen, Presse- und Medienanfragen, Partnerschafts- oder Lizenzfragen sowie technische Probleme beim Zugriff auf Novara News.',
            'Korrekturen: Bitte geben Sie die Artikel-URL oder Überschrift an, die betreffende Passage sowie Links zu Primärquellen oder offiziellen Dokumenten, die Ihre Korrektur belegen. Klare, gut belegte Meldungen ermöglichen eine schnelle Prüfung und – wenn nötig – eine aktualisierte Fassung mit Korrekturvermerk.',
            'Nachrichtentipps: Beschreiben Sie, was, wo und wann geschehen ist, und fügen Sie Nachweise bei, die Sie sicher teilen können – Dokumente, Protokolle, eine Chronologie der Ereignisse. Wir prüfen Tipps auf Verifizierbarkeit und echten öffentlichen Belang. Vertraulichkeitswünsche werden ernst genommen, können aber nicht in jedem Fall garantiert werden.',
            'Datenschutz und Datenrechte: Nennen Sie die gewünschte Maßnahme – Auskunft, Berichtigung, Löschung, Widerspruch oder ein anderes Recht – sowie die E-Mail-Adresse, unter der Sie mit uns in Kontakt standen. Für sensible Anträge kann eine Identitätsverifizierung erforderlich sein.',
            'Sicherheitslücken: Wenn Sie eine Schwachstelle in unseren Systemen entdeckt haben, nutzen Sie diese bitte nicht über einen Machbarkeitsnachweis hinaus aus. Senden Sie die Reproduktionsschritte über unseren Kontaktkanal mit dem Betreff „Sicherheit".',
            'Geschäftliche und rechtliche Schreiben sollten die vollständige Bezeichnung der Organisation, die Rechtsordnung und ein Aktenzeichen enthalten. Wir sichten alle Korrespondenz, können jedoch über das öffentliche Kontaktformular keine Rechtsberatung leisten.',
            'Wir streben an, schwerwiegende sachliche Meldungen in angemessener Frist zu bestätigen. Volumen und Verifizierungsaufwand können dazu führen, dass allgemeine Rückmeldungen oder weniger dringliche Anfragen mehr Zeit in Anspruch nehmen.',
        ],
    ],
];
