<?php

return [
    'about' => [
        'meta_description' => 'Novara News es una redacción digital independiente y multilingüe especializada en IA, ciberseguridad y tecnología emergente, con estándares editoriales profesionales en cinco idiomas.',
        'paragraphs' => [
            'Novara News es un medio digital independiente dedicado a los temas que definen la era tecnológica: grandes modelos de lenguaje y política de IA, competencia en semiconductores, infraestructura en la nube, incidentes de ciberseguridad, dispositivos de consumo, software empresarial, videojuegos y las fuerzas económicas que los transforman.',
            'Publicamos en cinco idiomas — inglés, turco, alemán, francés y español. Cada edición está diseñada para sus lectores: los titulares reflejan el registro propio de cada lengua, los matices cruzan correctamente la barrera idiomática y las estructuras de URL son nativas para cada mercado. Ningún artículo de este sitio es el resultado de una traducción automática a partir de un archivo fuente único.',
            'Nuestra cobertura sigue las categorías de la navegación: investigación y gobernanza de la IA, desarrollos en chips y la nube, ecosistemas móviles, software empresarial y de consumo, incidentes de seguridad y hardware. Elegimos los temas por su verificabilidad, interés público y proporcionalidad — no por petición de socios comerciales.',
            'Independencia: la redacción selecciona y enfoca la cobertura sin instrucciones de anunciantes, patrocinadores ni socios comerciales. El contenido patrocinado o de marca, cuando existe en el sitio, está claramente separado del contenido editorial y etiquetado conforme a nuestra política.',
            'Verificación: trabajamos con fuentes citadas por su nombre, documentos primarios, comunicados oficiales de reguladores y fabricantes, agencias de noticias de referencia y, en la cobertura científica, literatura revisada por pares. Distinguimos claramente lo que está confirmado, lo que es atribuido, lo que es análisis y lo que es especulación.',
            'Transparencia sobre el uso de IA: las herramientas de IA pueden apoyar la recopilación de investigación o la estructuración de borradores. Editores humanos revisan y autorizan cada versión publicable y asumen la plena responsabilidad de la exactitud, el contexto y la equidad. Toda participación significativa de la IA en la producción se comunica abiertamente a los lectores.',
            'Las correcciones son parte del periodismo serio, no una debilidad. Cuando modificamos el fondo de un artículo, publicamos una nota de corrección fechada que explica qué era erróneo y qué lo reemplaza. Las correcciones tipográficas sin impacto en el significado pueden realizarse sin aviso independiente.',
            'Tono y ética: no publicamos titulares que exageren la certeza, amplifiquen la alarma o reduzcan cuestiones técnicas complejas a una falsa simplicidad. La privacidad, la seguridad y la dignidad humana — especialmente de las personas privadas — orientan cada decisión editorial sobre qué publicar y cómo.',
            'Transparencia y descubrimiento: mantenemos URL de artículos estables, marcas de tiempo de publicación y actualización visibles, páginas completas de Quiénes somos, Política editorial, Contacto, Privacidad y Cookies, así como datos estructurados compatibles con Google Noticias, la Búsqueda de Google y las principales plataformas de agregación.',
            'Publicidad y analítica: cuando Google Analytics, Google AdSense u otros servicios comparables están activos, su uso se ajusta a nuestras políticas de privacidad y cookies y a los requisitos de consentimiento aplicables. Ninguna etiqueta comercial influye en las decisiones editoriales.',
            'Retroalimentación: las solicitudes serias de corrección respaldadas por fuentes primarias, los avisos de noticias y las divulgaciones responsables de vulnerabilidades de seguridad son bienvenidos a través de nuestros canales de contacto. Priorizamos las impugnaciones de buena fe que incluyen referencias verificables.',
            'Correspondencia legal y de prensa: los escritos institucionales deben identificar claramente la entidad, la jurisdicción y el asunto. No estamos en posición de brindar asesoría jurídica a través de nuestro formulario público.',
        ],
    ],

    'editorial-policy' => [
        'meta_description' => 'Política editorial de Novara News: independencia, verificación de fuentes, divulgación del uso de IA, proceso de correcciones y separación estricta entre actividad comercial y decisiones de la redacción.',
        'paragraphs' => [
            'Esta política editorial se aplica a todas las ediciones idiomáticas y secciones de Novara News. Describe cómo asignamos, verificamos, corregimos y etiquetamos los contenidos para que lectores y plataformas puedan entender los estándares que respaldan cada artículo publicado.',
            'Misión: cubrimos inteligencia artificial y tecnología para un público amplio que necesita información fiable y bien contextualizada — fundadores, observadores de políticas, ingenieros y lectores curiosos de todo perfil. Nuestro criterio es la exactitud y la proporcionalidad, no los ciclos de sensacionalismo ni las influencias comerciales ocultas.',
            'Independencia: la redacción elige los temas según hechos verificables, relevancia editorial y necesidades de la audiencia. Ningún anunciante, patrocinador, gobierno ni partido político puede dictar titulares, selección de temas o el enfoque del periodismo independiente. Las relaciones comerciales se mantienen estrictamente separadas de las decisiones editoriales.',
            'Exactitud y claridad: representamos honestamente los grados de certeza. Las noticias en desarrollo se actualizan a medida que los hechos se consolidan. Los análisis y formatos explicativos están redactados o señalizados de modo que los lectores distingan cuándo hay interpretación en lugar de hechos confirmados.',
            'Jerarquía de fuentes: preferimos fuentes con nombre, documentos primarios y agencias de noticias serias. El anonimato es excepcional, debe cumplir criterios internos estrictos y requiere una justificación editorial documentable.',
            'Divulgación de IA: cuando herramientas generativas o de asistencia han contribuido de forma significativa a la investigación, la redacción o el trabajo con datos, esto debe declararse. La redacción examina estas declaraciones y las comunica a los lectores cuando se alcanzan los umbrales establecidos en la política.',
            'Proceso de correcciones: los errores sustantivos se corrigen con rapidez, con una nota de corrección visible. Si la conclusión de un artículo cambia de forma significativa, explicamos el motivo. Las retractaciones se reservan para fallos factuales o éticos graves y se gestionan con plena transparencia.',
            'Integridad visual: las imágenes, gráficos y capturas de pantalla llevan pies de foto precisos. El material ilustrativo o simulado está claramente identificado para no confundirse con pruebas documentales.',
            'Seguridad: no publicamos instrucciones que puedan causar daños graves, credenciales sin enmascarar ni datos personales innecesarios. La cobertura de seguridad equilibra cuidadosamente el interés público con las normas de divulgación responsable.',
            'Separación entre redacción y publicidad: las unidades comerciales no pueden prometer ni solicitar cobertura favorable. Los formatos comerciales, las cajas de afiliados y las publicaciones de socios están claramente diferenciados del contenido periodístico y cumplen todos los requisitos de etiquetado aplicables.',
            'Diversidad y proporcionalidad: la tecnología afecta a personas de todo el mundo; en la medida en que la agenda informativa lo permite, buscamos una cobertura geográfica y demográficamente representativa, sin fabricar equilibrios falsos sobre hechos bien establecidos.',
            'Contenido de terceros y usuarios: las funciones de comentarios o comunidad, si existen, se moderan según reglas publicadas. Las declaraciones de usuarios no verificadas no equivalen a un reportaje validado por la redacción.',
            'Actualizaciones: esta política puede evolucionar con el avance tecnológico, la regulación y las expectativas de las plataformas. Los cambios sustanciales se reflejarán en esta página con una fecha de referencia actualizada.',
        ],
    ],

    'privacy' => [
        'meta_description' => 'Política de privacidad de Novara News: qué datos personales tratamos, con qué finalidad, con qué proveedores y cómo ejercer sus derechos de protección de datos.',
        'paragraphs' => [
            'Esta política de privacidad explica cómo Novara News («nosotros») gestiona la información cuando usted visita nuestro sitio, utiliza formularios o accede a funciones vinculadas a una cuenta o a comunicaciones por correo electrónico. Tratamos los datos personales de manera lícita, transparente y proporcionada.',
            'Responsable del tratamiento: la organización que opera Novara News en el dominio donde se publica esta política. Los datos de contacto para consultas sobre privacidad están disponibles en nuestra página de Contacto.',
            'Los datos que podemos recopilar incluyen: datos técnicos como direcciones IP truncadas, user-agents del navegador, clase de dispositivo y geografía aproximada derivada de señales de red; datos de uso como páginas vistas y eventos de interacción; e información que usted envía voluntariamente a través de formularios — por ejemplo, nombre, dirección de correo electrónico y texto del mensaje.',
            'Los mensajes de contacto y los avisos de noticias se utilizan para responderle, gestionar el seguimiento y mantener un registro proporcionado para cumplimiento normativo o gestión de reclamaciones. No vendemos datos personales ni utilizamos los canales de avisos para crear listas de marketing no solicitado.',
            'Contamos con encargados del tratamiento, entre ellos proveedores de alojamiento, servicios CDN y de seguridad (p. ej. Cloudflare), socios de envío de correo, proveedores de analítica y socios publicitarios. Todos están vinculados contractualmente a tratar los datos únicamente según instrucciones documentadas.',
            'Las cookies y tecnologías similares incluyen: cookies estrictamente necesarias para la seguridad, el equilibrio de carga, el almacenamiento del consentimiento y la navegación básica; cookies de preferencias que pueden guardar opciones como el tema de color o el idioma; cookies de análisis que miden el rendimiento agregado del sitio; y — donde aplique — cookies publicitarias para la limitación de frecuencia, la prevención del fraude y la medición en redes como Google AdSense, sujetas a sus opciones y a los requisitos regionales aplicables.',
            'Google Analytics: cuando está activo, podemos utilizar Google Analytics 4 para analizar el tráfico agregado del sitio. Puede gestionar sus preferencias de análisis y publicidad a través de la configuración del navegador, las herramientas de consentimiento regionales disponibles y las páginas de exclusión voluntaria de los proveedores.',
            'Google AdSense y etiquetas publicitarias similares: cuando están activos, los socios publicitarios pueden tratar datos conforme a sus propias políticas. Configuramos las etiquetas para respetar las señales de consentimiento aplicables y la normativa vigente. El contenido editorial se produce de forma independiente del targeting publicitario.',
            'Las bases legales pueden incluir intereses legítimos (operación segura, comprensión de la audiencia, prevención del fraude), ejecución de un contrato (atender sus solicitudes) y consentimiento cuando sea necesario para cookies no esenciales o marketing directo.',
            'La conservación se limita a las necesidades operativas. Los registros del servidor y la telemetría de seguridad se mantienen en ventanas rotativas cortas, salvo que una respuesta a incidentes u obligación legal requiera un período mayor. La correspondencia se conserva solo el tiempo necesario para resolver la consulta y cumplir las obligaciones normativas.',
            'Transferencias internacionales: si los datos salen de su país, implementamos las garantías adecuadas, como cláusulas contractuales tipo u otras medidas equivalentes, según lo exija el derecho aplicable.',
            'Seguridad: aplicamos controles conformes a los estándares del sector, incluyendo cifrado TLS, restricciones de acceso, supervisión y diligencia debida con los proveedores. Ningún servicio en línea está completamente libre de riesgos; le rogamos que informe de cualquier vulnerabilidad sospechosa a través de nuestros canales de contacto.',
            'Sus derechos: según su jurisdicción, puede solicitar acceso, rectificación, supresión, limitación, oposición o portabilidad de sus datos. Es posible que verifiquemos su identidad antes de atender su solicitud. También tiene derecho a presentar una reclamación ante su autoridad de control.',
            'Menores: nuestros servicios están destinados a adultos. No recopilamos conscientemente información personal de menores sin el consentimiento adecuado. Póngase en contacto con nosotros si cree que se han enviado datos de un menor por error.',
            'Cambios: actualizaremos esta política cuando cambien nuestras prácticas, socios o la legislación aplicable. El uso continuado tras actualizaciones sustanciales implica la aceptación en la medida permitida por la ley; los cambios importantes se anunciarán en el sitio.',
        ],
    ],

    'cookies' => [
        'meta_description' => 'Uso de cookies en Novara News: funcionamiento esencial del sitio, medición de audiencia, preferencias publicitarias y opciones prácticas para gestionar su consentimiento.',
        'paragraphs' => [
            'Las cookies y tecnologías de almacenamiento similares ayudan a Novara News a operar de forma segura, recordar sus preferencias, medir tendencias de audiencia y — cuando están habilitadas — apoyar una publicidad responsable. Esta página explica cada categoría y sus opciones de gestión.',
            'Las cookies estrictamente necesarias habilitan funciones de seguridad, reparten la carga del servidor, mantienen la integridad de las sesiones para las herramientas administrativas y respetan las elecciones de consentimiento que usted ya ha realizado. Desactivarlas puede deteriorar partes esenciales del sitio.',
            'Las cookies de preferencias recuerdan opciones como el tema de color o los accesos directos de idioma, cuando están disponibles. Su uso se limita a mejorar la usabilidad en nuestros propios dominios y no se emplea para el seguimiento entre sitios de terceros.',
            'Las cookies analíticas aportan estadísticas agregadas sobre la audiencia — secciones populares, rutas de navegación y tipos de dispositivos aproximados. Utilizamos estos datos para mejorar nuestras decisiones editoriales y técnicas, no para crear perfiles individuales con fines de marketing ajenos a nuestra actividad.',
            'Las cookies publicitarias, cuando AdSense u otras redes de publicidad están activas, pueden medir impresiones, limitar la frecuencia de exposición y detectar tráfico no válido. Los socios tratan los datos según sus propias políticas publicadas; consulte los recursos de Google sobre publicidad y privacidad para los detalles relativos a los servicios de Google.',
            'Gestión de sus cookies: puede eliminar o bloquear las cookies en la configuración del navegador, utilizar las páginas de exclusión voluntaria de los proveedores y — cuando ofrecemos una interfaz de consentimiento — retirar o actualizar su consentimiento en cualquier momento. Bloquear las cookies publicitarias no elimina todos los anuncios en todas las configuraciones, pero sí limita las experiencias publicitarias personalizadas.',
            'La señal «Do Not Track» del navegador no tiene aplicación uniforme en el sector. No obstante, aplicamos todos los controles e informaciones descritos en esta política y en nuestra política de privacidad.',
            'Actualizaciones: las categorías de cookies que utilizamos pueden cambiar con los proveedores, los servicios o la normativa. Le recomendamos revisar esta página periódicamente; los cambios importantes se anunciarán en el sitio cuando corresponda.',
        ],
    ],

    'contact' => [
        'meta_description' => 'Contacto de Novara News: correcciones, avisos confidenciales, solicitudes de prensa, privacidad de datos y colaboraciones relacionadas con nuestra cobertura de IA y tecnología.',
        'contact_label' => 'Contacto',
        'paragraphs' => [
            'Utilice el formulario seguro a continuación para ponerse en contacto con Novara News en relación con solicitudes de corrección, avisos de noticias, consultas sobre privacidad o derechos sobre datos, solicitudes de prensa y medios, preguntas de colaboración o licencia, y problemas técnicos que afecten al acceso al sitio.',
            'Correcciones: incluya la URL o el titular del artículo, el fragmento concreto en cuestión y enlaces a las fuentes primarias o documentos oficiales que respalden su corrección. Las solicitudes claras y bien documentadas permiten a los editores verificar con rapidez y, cuando proceda, publicar una versión actualizada con la correspondiente nota de corrección.',
            'Avisos de noticias: describa qué ocurrió, dónde y cuándo, aportando cualquier evidencia que pueda compartir de forma segura — documentos, registros, una cronología de los hechos. Evaluamos los avisos en función de su verificabilidad y su genuino interés público. Las solicitudes de confidencialidad se toman en serio, aunque no siempre pueden garantizarse.',
            'Privacidad y derechos sobre datos: especifique la acción solicitada — acceso, rectificación, supresión, oposición u otro derecho — y la dirección de correo electrónico asociada a su interacción con nosotros. Es posible que necesitemos verificar su identidad antes de tramitar solicitudes de carácter sensible.',
            'Vulnerabilidades de seguridad: si cree haber encontrado una vulnerabilidad en nuestros sistemas, no la explote más allá de una prueba de concepto. Envíe los pasos de reproducción a través de nuestro canal de contacto indicando en el asunto «Seguridad».',
            'Los avisos comerciales y legales deben incluir el nombre completo de la entidad, la jurisdicción y una referencia del asunto. Revisamos toda la correspondencia, pero no podemos ofrecer asesoría jurídica a través de nuestro formulario público.',
            'Nos proponemos acusar recibo de los informes factuales serios en un plazo razonable. El volumen de solicitudes y los requisitos de verificación pueden prolongar los tiempos de respuesta a la retroalimentación general o a las consultas no urgentes.',
        ],
    ],
];
