<?php

return [
    'variants' => [
        'generic' => [
            'labels' => [
                'data-lbl-title' => 'site.admin_seo_length_title',
                'data-lbl-description' => 'site.admin_seo_length_description',
                'data-lbl-title-px' => 'site.admin_seo_width_title',
                'data-lbl-description-px' => 'site.admin_seo_width_description',
                'data-lbl-ctr-label' => 'site.admin_seo_ctr_suggestion_label',
                'data-lbl-ctr-ok' => 'site.admin_seo_ctr_ok',
                'data-lbl-ctr-title-specific' => 'site.admin_seo_ctr_title_specific',
                'data-lbl-ctr-title-no-number' => 'site.admin_seo_ctr_title_no_number',
                'data-lbl-ctr-desc-value' => 'site.admin_seo_ctr_desc_value',
                'data-lbl-good' => 'site.admin_seo_length_good',
                'data-lbl-short' => 'site.admin_seo_length_short',
                'data-lbl-long' => 'site.admin_seo_length_long',
            ],
        ],
        'article' => [
            'labels' => [
                'data-lbl-title' => 'site.admin_seo_length_title',
                'data-lbl-description' => 'site.admin_seo_length_description',
                'data-lbl-title-px' => 'site.admin_seo_width_title',
                'data-lbl-description-px' => 'site.admin_seo_width_description',
                'data-lbl-good' => 'site.admin_seo_length_good',
                'data-lbl-short' => 'site.admin_seo_length_short',
                'data-lbl-long' => 'site.admin_seo_length_long',
                'data-lbl-ctr-label' => 'site.admin_seo_ctr_suggestion_label',
                'data-lbl-ctr-ok' => 'site.admin_seo_ctr_ok',
                'data-lbl-ctr-title-specific' => 'site.admin_seo_ctr_title_specific',
                'data-lbl-ctr-title-no-number' => 'site.admin_seo_ctr_title_no_number',
                'data-lbl-ctr-desc-value' => 'site.admin_seo_ctr_desc_value',
                'data-lbl-ctr-news' => 'site.admin_seo_ctr_news',
                'data-lbl-ctr-analysis' => 'site.admin_seo_ctr_analysis',
                'data-lbl-ctr-guide' => 'site.admin_seo_ctr_guide',
                'data-lbl-ctr-review' => 'site.admin_seo_ctr_review',
                'data-lbl-readiness-ready' => 'site.admin_readiness_status_pass',
                'data-lbl-readiness-warning' => 'site.admin_readiness_status_warn',
                'data-lbl-readiness-critical' => 'site.admin_readiness_status_fail',
                'data-lbl-readiness-check-title' => 'site.admin_article_readiness_check_title',
                'data-lbl-readiness-check-description' => 'site.admin_article_readiness_check_description',
                'data-lbl-readiness-check-noindex' => 'site.admin_article_readiness_check_noindex',
                'data-lbl-readiness-check-canonical' => 'site.admin_article_readiness_check_canonical',
                'data-lbl-readiness-check-og' => 'site.admin_article_readiness_check_og',
                'data-lbl-readiness-check-image' => 'site.admin_article_readiness_check_image',
                'data-lbl-readiness-check-alt' => 'site.admin_article_readiness_check_alt',
                'data-lbl-readiness-check-author' => 'site.admin_article_readiness_check_author',
                'data-lbl-readiness-help-title' => 'site.admin_article_readiness_help_title',
                'data-lbl-readiness-help-description' => 'site.admin_article_readiness_help_description',
                'data-lbl-readiness-help-noindex' => 'site.admin_article_readiness_help_noindex',
                'data-lbl-readiness-help-canonical' => 'site.admin_article_readiness_help_canonical',
                'data-lbl-readiness-help-og' => 'site.admin_article_readiness_help_og',
                'data-lbl-readiness-help-image' => 'site.admin_article_readiness_help_image',
                'data-lbl-readiness-help-alt' => 'site.admin_article_readiness_help_alt',
                'data-lbl-readiness-help-author' => 'site.admin_article_readiness_help_author',
                'data-lbl-tone-title' => 'site.admin_tone_guardrail_title',
                'data-lbl-tone-low' => 'site.admin_tone_guardrail_low',
                'data-lbl-tone-medium' => 'site.admin_tone_guardrail_medium',
                'data-lbl-tone-high' => 'site.admin_tone_guardrail_high',
                'data-lbl-tone-reason-generic' => 'site.admin_tone_reason_generic',
                'data-lbl-tone-reason-marketing' => 'site.admin_tone_reason_marketing',
                'data-lbl-tone-reason-stuffing' => 'site.admin_tone_reason_stuffing',
                'data-lbl-tone-reason-title' => 'site.admin_tone_reason_title',
                'data-lbl-tone-reason-desc' => 'site.admin_tone_reason_desc',
                'data-lbl-tone-reason-info' => 'site.admin_tone_reason_info',
                'data-lbl-tone-suggestion-specific' => 'site.admin_tone_suggestion_specific',
                'data-lbl-tone-suggestion-value' => 'site.admin_tone_suggestion_value',
                'data-lbl-tone-suggestion-marketing' => 'site.admin_tone_suggestion_marketing',
            ],
        ],
    ],
];
